spring:
  datasource:
    url: jdbc:mysql://localhost:3306/izanis-mysql
    username: izanis
    password: password
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      database-platform: org.hibernate.dialect.MySQL5Dialect
