# H2 database properties
spring:
  h2:
    console:
      enabled: true  # set to true to enable the H2 console
      path: /h2-console  # path at which the console will be available
  datasource:
    url: jdbc:h2:mem:testdb  # URL of the H2 database
    username: sa  # username for the H2 database, default is "sa"


# spring:
#   datasource:
#     platform: h2
#   jpa:
#     show-sql: true

# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/wardrobe
#     username: izanis
#     password: password
#     platform: mysql
#   jpa:
#     hibernate:
#       ddl-auto: validate
#     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#     database: mysql
#     show-sql: true
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: guru_database_create.sql