package io.noblackhole.wardrobe.wardrobebackend.domain;

public enum Material {
  ACRYLIC("Acrylic"), ANGORA("Angora"),
  ADHESIVE("Adhesive"), ALUMINUM("Aluminum"),
  BAMBOO("Bamboo"), CASHMERE("Cashmere"),
  BOA("Boa"), BURLAP("Burlap"),
  CARBON_FIBER("Carbon Fiber"), CARNELIAN("Carnelian"),
  CASHMERE_BLEND("Cashmere Blend"), CHAMBRAY("Chambray"),
  CHAMOIS("Chamois"), CHARMEUSE("Charmeuse"),
  CHIFFON("Chiffon"), COBALT("Cobalt"),
  CLAY("Clay"), CLOTH("Cloth"),
  COATED_FABRIC("Coated Fabric"), CORK("Cork"),
  COPPER("Copper"), CORDUROY("Corduroy"),
  COTTON("Cotton"), DENIM("Denim"),
  CRAPE("Crape"), CREPE_DE_CHINE("Crepe de Chine"),
  CREPE("Crepe"), EGYPTIAN_COTTON("Egyptian Cotton"),
  CRINKLED_RAYON("Crinkled Rayon"),
  CRINKLED_SYNTHETIC_FABRIC("Crinkled Synthetic Fabric"), CRINKLED_COTTON("Crinkled Cotton"),
  CROCHET("Crochet"), DIAMOND("Diamond"),
  DAMASK("Damask"), EMBROIDERED_FABRIC("Embroidered Fabric"),
  EMBROIDERY("Embroidery"), GABARDINE("Gabardine"),
  EMERALD("Emerald"), FAUX_FUR("Faux Fur"),
  FELT("Felt"), FLEECE("Fleece"),
  FLOCKED_FABRIC("Flocked Fabric"), GARNET("Garnet"),
  GAUZE("Gauze"), JERSEY("Jersey"),
  GEORGETTE("Georgette"), GORE_TEX("Gore-Tex"),
  GLASS("Glass"), GOLD("Gold"),
  GRANITE("Granite"), GRANULATED_LEATHER("Granulated Leather"),
  GROSGRAIN("Grosgrain"), HEMP("Hemp"),
  ILLUSION("Illusion"), JACQUARD("Jacquard"),
  JUTE("Jute"), KAPOK("Kapok"),
  KHAKI("Khaki"), KNIT("Knit"),
  LACE("Lace"), METAL("Metal"),
  LAMB_S_WOOL("Lamb's Wool"), MESH("Mesh"),
  LAME("Lame"), LAMINATED_FABRIC("Laminated Fabric"),
  LATEX("Latex"), LAVA("Lava"),
  LEATHER("Leather"), LINEN("Linen"),
  LEATHER_BLEND("Leather Blend"), LUCITE("Lucite"),
  LUREX("Lurex"), MALACHITE("Malachite"),
  LYCRA("Lycra"), MOHAIR("Mohair"),
  MARABOU("Marabou"), MARBLE("Marble"),
  MARCASITE("Marcasite"), MDF("MDF"),
  MICROFIBER("Microfiber"), ORGANIC_COTTON("Organic Cotton"),
  MINK("Mink"), MINK_FUR("Mink Fur"),
  MODAL("Modal"), MOORING("Mooring"),
  NEOPRENE("Neoprene"), OILCLOTH("Oilcloth"),
  NYLON("Nylon"), POLYESTER("Polyester"),
  OLEFIN("Olefin"),
  OPAQUE_TIGHTS("Opaque Tights"), ORIENTAL_RUG("Oriental Rug"),
  ORGANZA("Organza"), PIMA_COTTON("Pima Cotton"),
  ORLON("Orlon"), OSTRICH_FEATHER("Ostrich Feather"),
  OTHER("Other"), CERAMIC("Ceramic"),
  PADDED_FABRIC("Padded Fabric"), PAPER("Paper"),
  PATENT_LEATHER("Patent Leather"),
  PATTERNED_FABRIC("Patterned Fabric"), PAVE("Pave"),
  PEARL("Pearl"), PLASTIC("Plastic"),
  PEARL_BLEND("Pearl Blend"), PEARLED("Pearled"),
  PELT("Pelt"), PEWTER("Pewter"),
  PILE("Pile"), PLUSH("Plush"),
  POCKETING("Pocketing"), POLY_BLEND("Poly Blend"),
  POLAR_FLEECE("Polar Fleece"), RAMIE("Ramie"),
  POLYETHYLENE("Polyethylene"), POLYVINYL_CHLORIDE("Polyvinyl Chloride"),
  POLYURETHANE("Polyurethane"), PRECIOUS_STONE("Precious Stone"),
  PONTE_DE_ROMA("Ponte de Roma"), RATTAN("Rattan"),
  RAYON("Rayon"), RUBBER("Rubber"),
  RAYON_BLEND("Rayon Blend"), SEERSUCKER("Seersucker"),
  RAYON_JERSEY("Rayon Jersey"), RAYON_TWILL("Rayon Twill"),
  RINFOCO("Rinfoco"), RUBY("Ruby"),
  RUBY_BLEND("Ruby Blend"), RUBY_FABRIC("Ruby Fabric"),
  SABLE("Sable"), SAPPHIRE_BLEND("Sapphire Blend"),
  SAPPHIRE_FABRIC("Sapphire Fabric"), SATIN_JERSEY("Satin Jersey"),
  SATIN("Satin"), SILVER("Silver"),
  SATIN_TWILL("Satin Twill"), SCRUB("Scrub"),
  SEQUIN("Sequin"),
  SHANTUNG("Shantung"), SHEEPSKIN("Sheepskin"),
  SHEARLING("Shearling"), SHELL("Shell"),
  SHELLAC("Shellac"), SHIMMER("Shimmer"),
  SHINY("Shiny"), SHRINKABLE_FABRIC("Shrinkable Fabric"),
  SILK("Silk"), SPANDEX("Spandex"),
  SILVER_BLEND("Silver Blend"), SNAKESKIN("Snakeskin"),
  SPANDEX_BLEND("Spandex Blend"), SYNTHETIC_BLEND("Synthetic Blend"),
  SPANDEX_JERSEY("Spandex Jersey"), SPANDEX_TWILL("Spandex Twill"),
  STONE("Stone"),
  SUEDE("Suede"), TWEED("Tweed"),
  SUEDE_BLEND("Suede Blend"), SUNBRELLA("Sunbrella"),
  SWAROVSKI_CRYSTAL("Swarovski Crystal"), SYNTHETIC_FABRIC("Synthetic Fabric"),
  TEDDY("Teddy"), TITANIUM("Titanium"),
  TERRY_CLOTH("Terry Cloth"), TIGER_S_EYE("Tiger's Eye"),
  TIN("Tin"), TINY_BEADS("Tiny Beads"),
  TISSUE_WEIGHT_FABRIC("Tissue Weight Fabric"), TLC("TLC"),
  TONAL("Tonal"), TOPAZ("Topaz"),
  TOPAZ_BLEND("Topaz Blend"), TOPAZ_FABRIC("Topaz Fabric"),
  TRICOT("Tricot"), TWILL("Twill"),
  TROPICAL_WEIGHT_WOOL("Tropical Weight Wool"), TUBE_SOCKS("Tube Socks"),
  TULLE("Tulle"), VEGAN_LEATHER("Vegan Leather"),
  TWEED_BLEND("Tweed Blend"), TYVEK("Tyvek"),
  ULTRASUEDE("Ultrasuede"), UNFINISHED_LEATHER("Unfinished Leather"),
  UX_FUR("UX Fur"), CRINKLED_SYNTHETIC_MATERIAL("Crinkled Synthetic Material"),
  VELOUR("Velour"), ACETATE("Acetate"),
  VELVET("Velvet"), VINYL("Vinyl"),
  VELVETEEN("Velveteen"), VIBRANT("Vibrant"),
  VINYL_COATED_FABRIC("Vinyl Coated Fabric"), VISCOSE_BLEND("Viscose Blend"),
  VISCOSE("Viscose"), WOOD("Wood"),
  WALLPAPER("Wallpaper"),
  WATERPROOF("Waterproof"), WAXED_FABRIC("Waxed Fabric"),
  WET_SUIT_MATERIAL("Wet Suit Material"), WHITE_GOLD("White Gold"),
  WHITE_GOLD_BLEND("White Gold Blend"), WHITE_GOLD_FABRIC("White Gold Fabric"),
  WICKING("Wicking"), WINDPROOF("Windproof"),
  WOOL("Wool"),
  WOOL_BLEND("Wool Blend"), WOVEN("Woven"),
  WOVEN_BLEND("Woven Blend"), YAK_HAIR("Yak Hair"),
  YAK_HAIR_BLEND("Yak Hair Blend"), YAK_HAIR_FABRIC("Yak Hair Fabric"),
  YARN("Yarn"), STRAW("Straw"),
  YARN_BLEND("Yarn Blend"), YELLOW_GOLD("Yellow Gold"),
  YELLOW_GOLD_BLEND("Yellow Gold Blend"), YELLOW_GOLD_FABRIC("Yellow Gold Fabric");
  private final String material;

  Material(String material) {
    this.material = material;
  }

  public String getMaterial() {
    return material;
  }
}